# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SearchCar' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SearchCar

pod 'AFNetworking', '~> 3.2.1'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'YYKit', '~> 1.0.9'
pod 'IQKeyboardManager', '~> 6.2.0'
pod 'Masonry', '~> 1.1.0'
pod 'ReactiveCocoa','~>2.1.8'
pod 'JPush'

end
